# Generated by Django 5.0.6 on 2024-06-13 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="description",
            field=models.TextField(blank=True, max_length=256),
        ),
    ]
