# Generated by Django 5.0.6 on 2024-06-13 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demo", "0002_book_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
