# Generated by Django 5.0.6 on 2024-06-13 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demo", "0003_book_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="cover",
            field=models.ImageField(blank=True, upload_to="covers/"),
        ),
        migrations.AddField(
            model_name="book",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="book",
            name="published",
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
